AWSTemplateFormatVersion: '2010-09-09'
Description: 'Unite Backend Assignment: Fixed Network'

Parameters:
  DBPassword:
    Type: String
    Description: 'Password for RDS MySQL'
    NoEcho: true
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: 'Name of an existing EC2 KeyPair for SSH access'

Resources:
  # 1. S3 Bucket (unchanged)
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  # 2. Security Group (Explicitly allowing RDS port 3306)
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Allow HTTP/SSH/MySQL access'
      # No VpcId specified -> uses Default VPC automatically
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0 # Allows RDS access

  # 3. RDS Instance (Uses VPCSecurityGroups)
  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: 'unite-db-v2'
      Engine: MySQL
      EngineVersion: '8.0'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      MasterUsername: 'admin'
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: true # Set to true so it uses public subnets easily
      VPCSecurityGroups:
        - !GetAtt WebServerSecurityGroup.GroupId # FORCE ID retrieval

  # 4. IAM Role (unchanged)
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ['s3:PutObject', 's3:GetObject']
                Resource: !Sub 'arn:aws:s3:::${AppBucket}/*'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref EC2InstanceRole]

  # 5. EC2 Instance (unchanged)
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c614dee691cbbf37 # US-EAST-1 Amazon Linux 2023
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y ruby wget
          cd /home/ec2-user
          wget https://aws-codedeploy-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto

Outputs:
  InstancePublicIP:
    Description: Public IP of EC2
    Value: !GetAtt MyEC2Instance.PublicIp
  BucketName:
    Description: S3 Bucket
    Value: !Ref AppBucket
  RDSEndpoint:
    Description: RDS Connect String
    Value: !GetAtt MyRDSInstance.Endpoint.Address
